version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresdb:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_DB=app
      - POSTGRES__PASSWORD=pass
    ports:
      - '5432:5432'

  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'